# Generated by Django 4.0.6 on 2022-08-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_rename_desc_team_desc1_rename_img_team_img1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='desc1',
            new_name='desc2',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img1',
            new_name='img2',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name1',
            new_name='name2',
        ),
    ]
